# Generated by Django 5.0.6 on 2024-06-16 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='flan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flan_uuid', models.UUIDField()),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('precio_publico_general', models.IntegerField()),
                ('precio_publico_logueado', models.IntegerField()),
                ('image_url', models.URLField()),
                ('url', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('is_prived', models.BooleanField()),
                ('stock', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
