# Generated by Django 5.0.6 on 2024-06-18 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0003_suscripcion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Suscripcion',
            new_name='SuscripcionForm',
        ),
    ]
